# Generated by Django 4.1.5 on 2023-01-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='activation_code',
            field=models.UUIDField(auto_created=True, blank=True, null=True),
        ),
    ]
