# Generated by Django 4.1.5 on 2023-01-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_managers_usermodel_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='activation_code',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
