# Generated by Django 4.1.5 on 2023-01-22 19:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GauntletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('reroll_points_const', models.PositiveIntegerField(default=1)),
                ('first_finished_points_award', models.PositiveIntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Gauntlet',
                'verbose_name_plural': 'Gauntlets',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GauntletStageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', models.PositiveIntegerField(choices=[(1, 'Easy'), (2, 'Normal'), (3, 'Hard')], default=2)),
                ('length', models.PositiveIntegerField(choices=[(1, 'Short'), (2, 'Normal'), (3, 'Long')], default=2)),
                ('gauntlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gauntlets.gauntletmodel')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.platformmodel')),
                ('prev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='gauntlets.gauntletstagemodel')),
            ],
            options={
                'verbose_name': 'Gauntlet stage',
                'verbose_name_plural': 'Gauntlet stages',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GauntletParticipantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gauntlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gauntlets.gauntletmodel')),
            ],
            options={
                'verbose_name': 'Gauntlet participant',
                'verbose_name_plural': 'Gauntlet participants',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
