# Generated by Django 4.1.5 on 2023-01-12 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lengthfeedbackmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.platformmodel'),
        ),
        migrations.AddField(
            model_name='difficultyfeedbackmodel',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamemodel'),
        ),
        migrations.AddField(
            model_name='difficultyfeedbackmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
