# Generated by Django 4.1.5 on 2023-01-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='platformmodel',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
